version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: multitenant_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - multitenant_network
    command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

  # MongoDB Service
  mongodb:
    image: mongo:6
    container_name: multitenant_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - multitenant_network
    command: mongod --auth

  # Redis Service
  redis:
    image: redis:7
    container_name: multitenant_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - multitenant_network
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  multitenant_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
